### ISSUE TITLE
Graphical User Interface for it in the form of a Toolbar that goes in the Taskbar

### ISSUE THREAD

**Issue by Zero3K** [jay/battstatus#1]
It would be nice if it could be made to have a Graphical User Interface for it in the form of a Toolbar that goes in the Taskbar (with features found in BatteryBar Pro - https://batterybarpro.com - added to it).

**Comment by jay** [comment]
Thank you for the feedback. I don't plan to add that. It's too much work for what I wrote as a text utility.

**Comment by Zero3K** [comment]
Maybe someone else could do it.
