### ISSUE TITLE
Add a command line parameter to show the battery's information

### ISSUE THREAD

**Issue by Zero3K** [jay/battstatus#2]
It would be nice if you could do that.

**Comment by jay** [comment]
I think you can get that information in verbose mode.

**Comment by Zero3K** [comment]
It doesn't show the kind of information that Battery Mode (https://en.bmode.tarcode.ru/) shows.

**Comment by jay** [comment]
It looks like it gives the same information. What specifically?

**Comment by Zero3K** [comment]
![image](https://user-images.githubusercontent.com/6194332/164959076-7678f2a1-ab35-4952-88a6-d774bff7bb01.png)

**Comment by jay** [comment]
I think much of that information should be available in verbose mode.

**Comment by Zero3K** [comment]
All I get is the following:

--- Sun Apr 24 02:01:14 AM ---
ACLineStatus:         Online
BatteryFlag:          Low | Charging
BatteryLifePercent:   26%
SystemStatusFlag:     Battery saver is off
BatteryLifeTime:      Unknown
BatteryFullLifeTime:  Unknown
Battery Power Rate:   +43103mW (or relative)

**Comment by jay** [comment]
There are multiple levels of verbose mode. Try -vvv

**Comment by Zero3K** [comment]
Actually, -v worked. I just didn't scroll up.

**Comment by jay** [comment]
Ok
