### ISSUE TITLE
Hiding the date and time shown in the title bar

### ISSUE THREAD

**Issue by Zero3K** [jay/battstatus#5]
It would be nice if you could do that.

**Comment by jay** [comment]
No. If you need something more specific then you can fork and modify the code.

**Comment by Zero3K** [comment]
How about an option?

**Comment by jay** [comment]
No.

**Comment by jay** [comment]
I changed my mind and re-released [v1.4](https://github.com/jay/battstatus/releases/tag/v1.4) without the timestamp in the window title.

**Comment by Zero3K** [comment]
Thanks.
